server:
  port: 8445

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yooblog?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

